const state={files:[],selected:null,original:'',current:'',model:null};
function callStudio(payload){return new Promise((resolve,reject)=>{const requestId=Math.random().toString(36).slice(2)+Date.now();function handler(event){if(!event.data||event.data.requestId!==requestId)return;window.removeEventListener('message',handler);event.data.error?reject(new Error(event.data.error)):resolve(event.data.result)}window.addEventListener('message',handler);window.parent.postMessage({requestId,payload},'*')})}
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function parseTraw(text){const lines=String(text??'').replace(/\r\n?/g,'\n').split('\n');let title='',sections=[],section=null,seenTitle=false;for(const raw of lines){if(!raw.trim())continue;const m=raw.trim().match(/^\[([^\]]+)\]$/);if(m){if(!seenTitle){title=m[1];seenTitle=true}else{section={key:m[1],lines:[]};sections.push(section)}continue}if(!section){section={key:'',lines:[]};sections.push(section)}section.lines.push(raw)}return{title,sections}}
function serialize(m){const out=[`[${m.title||'Sem título'}]`];for(const s of m.sections){out.push('',`[${s.key}]`,...s.lines)}return out.join('\n')+'\n'}
function status(s){$('statusText').textContent=s} function dirty(){const d=state.current!==state.original;$('dirtyStatus').textContent=d?'● Modificado':'';$('saveBtn').disabled=!state.selected||!d;$('revertBtn').disabled=!state.selected||!d;const f=state.files.find(x=>x.name===state.selected);$('deleteBtn').disabled=!f||f.builtIn}
function renderFiles(){const el=$('fileList');el.innerHTML='';for(const f of state.files){const b=document.createElement('div');b.className=`file-item${f.builtIn?' builtin':''}${state.selected===f.name?' active':''}`;b.tabIndex=0;b.setAttribute('role','button');b.innerHTML=`<div class="file-badge">${f.builtIn?'TR':'✎'}</div><div class="file-info"><div class="file-name-small">${esc(f.name)}.traw</div><div class="file-kind">${f.builtIn?'Arquivo integrado':'Arquivo customizado'}</div></div>${f.builtIn?'':'<button class="file-delete-btn" type="button" title="Excluir arquivo" aria-label="Excluir arquivo">🗑</button>'}`;b.onclick=()=>openFile(f.name);b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openFile(f.name)}};if(!f.builtIn){b.querySelector('.file-delete-btn').onclick=e=>{e.stopPropagation();deleteFile(f.name)}}el.appendChild(b)}$('fileCount').textContent=`${state.files.length} arquivo${state.files.length===1?'':'s'}`}
async function refresh(){try{status('Atualizando arquivos…');state.files=await callStudio({type:'list'});renderFiles();if(state.selected&&!state.files.some(f=>f.name===state.selected)){state.selected=null;showEmpty()}status('Pronto')}catch(e){status(e.message||'Erro ao listar arquivos')}}
function showEmpty(){$('fileName').textContent='Nenhum arquivo selecionado';$('fileMeta').textContent='Selecione um .traw';$('editorArea').className='editor-area empty';$('editorArea').innerHTML='<div class="empty-state"><div class="empty-logo">TR</div><h2>Editor de arquivos .traw</h2><p>Selecione um arquivo na esquerda ou crie um novo arquivo customizado.</p></div>';dirty()}
async function openFile(name){try{status(`Abrindo ${name}.traw…`);const c=await callStudio({type:'read',name});state.selected=name;state.original=c;state.current=c;state.model=parseTraw(c);renderEditor();renderFiles();status('Arquivo carregado')}catch(e){status(e.message||'Não foi possível abrir o arquivo')}}
function renderEditor(){const f=state.files.find(x=>x.name===state.selected),ro=!!f?.builtIn,m=state.model; $('fileName').textContent=`${state.selected}.traw`;$('fileMeta').textContent=ro?'Arquivo integrado • somente leitura':'Arquivo customizado • editável';const root=document.createElement('div');const title=document.createElement('div');title.className='title-editor';title.innerHTML=`<input id="titleInput" value="${esc(m.title)}" placeholder="Título do arquivo" ${ro?'disabled':''}>`;root.appendChild(title);m.sections.forEach((s,si)=>{const card=document.createElement('div');card.className='section';const head=document.createElement('div');head.className='section-head';const headLeft=document.createElement('div');headLeft.className='section-head-left';const keyInput=document.createElement('input');keyInput.className='section-title section-key-input';keyInput.value=s.key;keyInput.placeholder='chave-da-seção';keyInput.disabled=ro;keyInput.spellcheck=false;const keyPreview=document.createElement('div');keyPreview.className='section-key';keyPreview.textContent=`[${s.key}]`;keyInput.oninput=()=>{s.key=keyInput.value;keyPreview.textContent=`[${keyInput.value}]`;state.current=serialize(m);dirty()};headLeft.append(keyInput,keyPreview);head.appendChild(headLeft);card.appendChild(head);const lines=document.createElement('div');lines.className='section-lines';s.lines.forEach((line,li)=>{const row=document.createElement('div');row.className='line-row';const n=document.createElement('div');n.className='line-number';n.textContent=String(li+1).padStart(2,'0');const input=document.createElement('textarea');input.className='line-input';input.rows=Math.max(1,Math.ceil(Math.max(line.length,1)/90));input.value=line;input.disabled=ro;input.oninput=()=>{s.lines[li]=input.value;state.current=serialize(m);dirty()};row.append(n,input);lines.appendChild(row)});if(!ro){const add=document.createElement('button');add.className='add-line';add.textContent='＋ Adicionar linha';add.onclick=()=>{s.lines.push('');state.current=serialize(m);renderEditor();dirty()};lines.appendChild(add)}card.appendChild(lines);root.appendChild(card)});if(!ro){const addSec=document.createElement('button');addSec.className='add-line';addSec.textContent='＋ Adicionar seção';addSec.onclick=()=>{m.sections.push({key:`secao-${m.sections.length+1}`,lines:['']});state.current=serialize(m);renderEditor();dirty()};root.appendChild(addSec)}$('editorArea').className='editor-area';$('editorArea').replaceChildren(root);if(!ro)$('titleInput').oninput=e=>{m.title=e.target.value;state.current=serialize(m);dirty()};dirty()}
async function save(){if(!state.selected)return;const f=state.files.find(x=>x.name===state.selected);if(f?.builtIn)return;try{status('Salvando…');state.current=serialize(state.model);await callStudio({type:'write',name:state.selected,content:state.current});state.original=state.current;dirty();status('Salvo')}catch(e){status(e.message||'Erro ao salvar')}}
function revert(){if(!state.selected)return;state.current=state.original;state.model=parseTraw(state.original);renderEditor();status('Alterações revertidas')}
function openModal(){$('modalError').textContent='';$('newName').value='';$('newTitle').value='';$('newSection').value='dados';$('modal').classList.remove('hidden');$('newName').focus()}function closeModal(){$('modal').classList.add('hidden')}
async function createFile(){const raw=$('newName').value.trim(),name=raw.replace(/\.traw$/i,''),title=$('newTitle').value.trim()||name||'Novo arquivo',section=$('newSection').value.trim()||'dados';if(!name)return $('modalError').textContent='Informe um nome.';if(!/^[^\\/:*?"<>|]+$/.test(name))return $('modalError').textContent='Nome inválido.';try{await callStudio({type:'create',name,content:`[${title}]\n\n[${section}]\n`});closeModal();await refresh();await openFile(name)}catch(e){$('modalError').textContent=e.message||'Não foi possível criar o arquivo.'}}
function askConfirm(title,message){return new Promise(resolve=>{$('confirmTitle').textContent=title;$('confirmMessage').textContent=message;$('confirmModal').classList.remove('hidden');const cleanup=v=>{$('confirmModal').classList.add('hidden');$('confirmOk').onclick=null;$('confirmCancel').onclick=null;$('confirmClose').onclick=null;resolve(v)};$('confirmOk').onclick=()=>cleanup(true);$('confirmCancel').onclick=()=>cleanup(false);$('confirmClose').onclick=()=>cleanup(false)})}
async function deleteFile(name){const f=state.files.find(x=>x.name===name);if(!f||f.builtIn)return;const ok=await askConfirm('Excluir arquivo',`Excluir ${name}.traw? Essa ação não pode ser desfeita.`);if(!ok)return;try{status('Excluindo…');await callStudio({type:'delete',name});if(state.selected===name){state.selected=null;state.original='';state.current='';state.model=null;showEmpty()}await refresh();status('Arquivo excluído')}catch(e){status(e.message||'Erro ao excluir')}}
$('refreshBtn').onclick=refresh;$('newBtn').onclick=openModal;$('modalClose').onclick=closeModal;$('modalCancel').onclick=closeModal;$('modalCreate').onclick=createFile;$('saveBtn').onclick=save;$('revertBtn').onclick=revert;$('deleteBtn').onclick=()=>deleteFile(state.selected);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if(e.key==='Escape'){if(!$('confirmModal').classList.contains('hidden'))$('confirmCancel').onclick?.();closeModal()}});showEmpty();refresh();
